Add Sabari Nath to Chennai Astronomy Club list
ChennaiAstronomyClub/chennaiastronomyclub.github.io pull request #7
Opened 2018-04-24 09:48 UTC by BadMofocur

2018-04-26 18:05 UTC, astronomersiva requested changes

2018-04-26 18:05 UTC, astronomersiva commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +---
Please rename the file to something simpler. Also, do not use capital letters in file names. There will be weird issues because of this in Linux.

2018-04-26 18:05 UTC, astronomersiva commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +permalink: /2018/05/24/The-Ultimate-Guide-to-Choosing-Your-First-Telescope/
Please do not use upper case letters in URLs. Linux servers won't be able to serve this page if someone enters the URL in lowercase(which is what everyone does commonly).

2018-04-26 18:05 UTC, astronomersiva commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +# <b>The Ultimate Guide to Choosing Your First Telescope</b>
HTML Tags are not needed when markdown is used.

2018-04-26 18:05 UTC, astronomersiva commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +<br>
Just a blank line is sufficient. Please install Jekyll in your machine and run `jekyll serve` from this folder. You will be able to see the preview.

2018-04-26 18:05 UTC, astronomersiva commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +# <b>The Ultimate Guide to Choosing Your First Telescope</b>
This title is not needed here. The template automatically inserts it.

2018-04-26 18:05 UTC, astronomersiva commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +---
Please install Jekyll in your machine and run jekyll serve from this folder. You will be able to see the preview.

2018-04-26 18:05 UTC, astronomersiva commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +permalink: /2018/05/24/The-Ultimate-Guide-to-Choosing-Your-First-Telescope/
Please change the date in the file name and this place to a non-future date. Else it will be skipped.

2018-05-04 07:52 UTC, BadMofocur commented on _posts/2018-05-24-The-Ultimate-Guide-to-Choosing-Your-First-Telescope.md
> +---
Installed Ruby and Jekyll.

2018-05-04 07:55 UTC, BadMofocur commented
Done all the changes as requested.

2018-05-06 13:12 UTC, merged

2018-05-06 13:12 UTC, astronomersiva commented
@BadMofocur Thanks for working on this with patience :)